# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 329ac554715015a997918e5ce7de142a91c1f22e7728354dbd52bf780924d582de324ccaf229def37d6af9fa6d4d42749f70bc11e9ea84a1eac06ce07f46cdfb

test:
  secret_key_base: 1e513567e8376ae1a75c714c470d7b9e530cc594e153ebdf1dc3b747033a17353128bd49f6fcf0cd9a8585725d27e68fcda527ad93d98253d0d17fc21eb1018f

beta:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
